function [rx,ry,rz ] = AonVecVEL3Dper2(vhx,vhy,vhz,vcoef)


%Computes the residual r=f-Av because Ae=Au-Av=r
[Em,En,Ep]=size(vhx);
Emm=Em-1;
Enm=En-1;
Emmm=Em-2;
Enmm=En-2;
Epm=Ep-1;
Epmm=Ep-2;
% vhx=[vhx,vhx(:,2)];
rx=zeros(Em,En,Ep);
ry=rx;
rz=rx;



rx(2:Emm,2:Enm,2:Epm)=-vcoef.coefx.*vhx(2:Emm,2:Enm,2:Epm)+...
    2*vcoef.rescoefpp1.*vhx(2:Emm,3:En,2:Epm)+2*vcoef.rescoefpm1.*vhx(2:Emm,1:Enmm,2:Epm)+...
    vcoef.rescoefpp2.*vhx(3:Em,2:Enm,2:Epm)+vcoef.rescoefpm2.*vhx(1:Emmm,2:Enm,2:Epm)+...
    vcoef.rescoefpp3.*vhx(2:Emm,2:Enm,3:Ep)+vcoef.rescoefpm3.*vhx(2:Emm,2:Enm,1:Epmm)+...
    vcoef.viscpp2(:,1:Enmm,1:Epmm).*(vhy(3:Em,3:En,2:Epm)-vhy(3:Em,1:Enmm,2:Epm))+vcoef.viscpm2(:,1:Enmm,1:Epmm).*(vhy(1:Emmm,1:Enmm,2:Epm)-vhy(1:Emmm,3:En,2:Epm))...
    +vcoef.viscpp3(:,1:Enmm,1:Epmm).*(vhz(2:Emm,3:En,3:Ep)-vhz(2:Emm,1:Enmm,3:Ep))+vcoef.viscpm3(:,1:Enmm,1:Epmm).*(vhz(2:Emm,1:Enmm,1:Epmm)-vhz(2:Emm,3:En,1:Epmm));
% rx(:,1)=rx(:,Enm);

rx(2:Emm,En,2:Epm)=-vcoef.coefxboundR.*vhx(2:Emm,1,2:Epm)+...
    2*vcoef.rescoefpp1boundR.*vhx(2:Emm,2,2:Epm)+2*vcoef.rescoefpm1boundR.*vhx(2:Emm,Enm,2:Epm)+...
    vcoef.rescoefpp2boundR.*vhx(3:Em,En,2:Epm)+vcoef.rescoefpm2boundR.*vhx(1:Emmm,En,2:Epm)+...
    vcoef.rescoefpp3boundR.*vhx(2:Emm,En,3:Ep)+vcoef.rescoefpm3boundR.*vhx(2:Emm,En,1:Epmm)+...
    vcoef.viscpp2(:,Enm,1:Epmm).*(vhy(3:Em,2,2:Epm)-vhy(3:Em,Enm,2:Epm))+vcoef.viscpm2(:,Enm,1:Epmm).*(vhy(1:Emmm,Enm,2:Epm)-vhy(1:Emmm,2,2:Epm))...
    +vcoef.viscpp3(:,Enm,1:Epmm).*(vhz(2:Emm,2,3:Ep)-vhz(2:Emm,Enm,3:Ep))+vcoef.viscpm3(:,Enm,1:Epmm).*(vhz(2:Emm,Enm,1:Epmm)-vhz(2:Emm,2,1:Epmm));


rx(2:Emm,2:Enm,Ep)=-vcoef.coefxboundF.*vhx(2:Emm,2:Enm,Ep)+...
    2*vcoef.rescoefpp1boundF.*vhx(2:Emm,3:En,Ep)+2*vcoef.rescoefpm1boundF.*vhx(2:Emm,1:Enmm,Ep)+...
    vcoef.rescoefpp2boundF.*vhx(3:Em,2:Enm,Ep)+vcoef.rescoefpm2boundF.*vhx(1:Emmm,2:Enm,Ep)+...
    vcoef.rescoefpp3boundF.*vhx(2:Emm,2:Enm,2)+vcoef.rescoefpm3boundF.*vhx(2:Emm,2:Enm,Epm)+...
    vcoef.viscpp2(:,1:Enmm,Epm).*(vhy(3:Em,3:En,Ep)-vhy(3:Em,1:Enmm,Ep))+...
    vcoef.viscpm2(:,1:Enmm,Epm).*(vhy(1:Emmm,1:Enmm,Ep)-vhy(1:Emmm,3:En,Ep))...
    +vcoef.viscpp3(:,1:Enmm,Epm).*(vhz(2:Emm,3:En,2)-vhz(2:Emm,1:Enmm,2))+vcoef.viscpm3(:,1:Enmm,Epm).*(vhz(2:Emm,1:Enmm,Epm)-vhz(2:Emm,3:En,Epm));

rx(2:Emm,En,Ep)=-vcoef.coefxboundFR.*vhx(2:Emm,En,Ep)+...
    2*vcoef.rescoefpp1boundFR.*vhx(2:Emm,2,Ep)+2*vcoef.rescoefpm1boundFR.*vhx(2:Emm,Enm,Ep)+...
    vcoef.rescoefpp2boundFR.*vhx(3:Em,En,Ep)+vcoef.rescoefpm2boundFR.*vhx(1:Emmm,En,Ep)+...
    vcoef.rescoefpp3boundFR.*vhx(2:Emm,En,2)+vcoef.rescoefpm3boundFR.*vhx(2:Emm,En,Epm)+...
    vcoef.viscpp2(:,Enm,Epm).*(vhy(3:Em,2,Ep)-vhy(3:Em,Enm,Ep))+...
    vcoef.viscpm2(:,Enm,Epm).*(vhy(1:Emmm,Enm,Ep)-vhy(1:Emmm,2,Ep))...
    +vcoef.viscpp3(:,Enm,Epm).*(vhz(2:Emm,2,2)-vhz(2:Emm,Enm,2))+vcoef.viscpm3(:,Enm,Epm).*(vhz(2:Emm,Enm,Epm)-vhz(2:Emm,2,Epm));


    
    
ry(2:Emm,2:Enm,2:Epm)=-vcoef.coefy.*vhy(2:Emm,2:Enm,2:Epm)+...
    vcoef.rescoefpp1.*vhy(2:Emm,3:En,2:Epm)+vcoef.rescoefpm1.*vhy(2:Emm,1:Enmm,2:Epm)+...
    2*vcoef.rescoefpp2.*vhy(3:Em,2:Enm,2:Epm)+2*vcoef.rescoefpm2.*vhy(1:Emmm,2:Enm,2:Epm)+...
    vcoef.rescoefpp3.*vhy(2:Emm,2:Enm,3:Ep)+vcoef.rescoefpm3.*vhy(2:Emm,2:Enm,1:Epmm)+...
    vcoef.viscpp1(:,1:Enmm,1:Epmm).*(vhx(3:Em,3:En,2:Epm)-vhx(1:Emmm,3:En,2:Epm))+vcoef.viscpm1(:,1:Enmm,1:Epmm).*(vhx(1:Emmm,1:Enmm,2:Epm)-vhx(3:Em,1:Enmm,2:Epm))...
    +vcoef.viscpp3(:,1:Enmm,1:Epmm).*(vhz(3:Em,2:Enm,3:Ep)-vhz(1:Emmm,2:Enm,3:Ep))+vcoef.viscpm3(:,1:Enmm,1:Epmm).*(vhz(1:Emmm,2:Enm,1:Epmm)-vhz(3:Em,2:Enm,1:Epmm));

ry(2:Emm,En,2:Epm)=-vcoef.coefyboundR.*vhy(2:Emm,1,2:Epm)+...
    vcoef.rescoefpp1boundR.*vhy(2:Emm,2,2:Epm)+vcoef.rescoefpm1boundR.*vhy(2:Emm,Enm,2:Epm)+...
    2*vcoef.rescoefpp2boundR.*vhy(3:Em,En,2:Epm)+2*vcoef.rescoefpm2boundR.*vhy(1:Emmm,En,2:Epm)+...
    vcoef.rescoefpp3boundR.*vhy(2:Emm,En,3:Ep)+vcoef.rescoefpm3boundR.*vhy(2:Emm,En,1:Epmm)+...
    vcoef.viscpp1(:,Enm,1:Epmm).*(vhx(3:Em,2,2:Epm)-vhx(1:Emmm,2,2:Epm))+vcoef.viscpm1(:,Enm,1:Epmm).*(vhx(1:Emmm,Enm,2:Epm)-vhx(3:Em,Enm,2:Epm))...
    +vcoef.viscpp3(:,Enm,1:Epmm).*(vhz(3:Em,En,3:Ep)-vhz(1:Emmm,En,3:Ep))+vcoef.viscpm3(:,Enm,1:Epmm).*(vhz(1:Emmm,En,1:Epmm)-vhz(3:Em,En,1:Epmm));


ry(2:Emm,2:Enm,Ep)=-vcoef.coefyboundF.*vhy(2:Emm,2:Enm,Ep)+...
    vcoef.rescoefpp1boundF.*vhy(2:Emm,3:En,Ep)+vcoef.rescoefpm1boundF.*vhy(2:Emm,1:Enmm,Ep)+...
    2*vcoef.rescoefpp2boundF.*vhy(3:Em,2:Enm,Ep)+2*vcoef.rescoefpm2boundF.*vhy(1:Emmm,2:Enm,Ep)+...
    vcoef.rescoefpm3boundF.*vhy(2:Emm,2:Enm,Epm)+vcoef.rescoefpp3boundF.*vhy(2:Emm,2:Enm,2)+...
    vcoef.viscpp1(:,1:Enmm,Epm).*(vhx(3:Em,3:En,Ep)-vhx(1:Emmm,3:En,Ep))+vcoef.viscpm1(:,1:Enmm,Epm).*(vhx(1:Emmm,1:Enmm,Ep)-vhx(3:Em,1:Enmm,Ep))+...
    vcoef.viscpp3(:,1:Enmm,Epm).*(vhz(3:Em,2:Enm,2)-vhz(1:Emmm,2:Enm,2))+vcoef.viscpm3(:,1:Enmm,Epm).*(vhz(1:Emmm,2:Enm,Epm)-vhz(3:Em,2:Enm,Epm));

   
ry(2:Emm,En,Ep)=-vcoef.coefyboundFR.*vhy(2:Emm,En,Ep)+...
    vcoef.rescoefpp1boundFR.*vhy(2:Emm,2,Ep)+vcoef.rescoefpm1boundFR.*vhy(2:Emm,Enm,Ep)+...
    2*vcoef.rescoefpp2boundFR.*vhy(3:Em,En,Ep)+2*vcoef.rescoefpm2boundFR.*vhy(1:Emmm,En,Ep)+...
    vcoef.rescoefpm3boundFR.*vhy(2:Emm,En,Epm)+vcoef.rescoefpp3boundFR.*vhy(2:Emm,En,2)+...
    vcoef.viscpp1(:,Enm,Epm).*(vhx(3:Em,2,Ep)-vhx(1:Emmm,2,Ep))+vcoef.viscpm1(:,Enm,Epm).*(vhx(1:Emmm,Enm,Ep)-vhx(3:Em,Enm,Ep))+...
    vcoef.viscpp3(:,Enm,Epm).*(vhz(3:Em,En,2)-vhz(1:Emmm,En,2))+vcoef.viscpm3(:,Enm,Epm).*(vhz(1:Emmm,En,Epm)-vhz(3:Em,En,Epm));
    



    
rz(2:Emm,2:Enm,2:Epm)=-vcoef.coefz.*vhz(2:Emm,2:Enm,2:Epm)+...
    vcoef.rescoefpp1.*vhz(2:Emm,3:En,2:Epm)+vcoef.rescoefpm1.*vhz(2:Emm,1:Enmm,2:Epm)+...
    vcoef.rescoefpp2.*vhz(3:Em,2:Enm,2:Epm)+vcoef.rescoefpm2.*vhz(1:Emmm,2:Enm,2:Epm)+...
    2*vcoef.rescoefpp3.*vhz(2:Emm,2:Enm,3:Ep)+2*vcoef.rescoefpm3.*vhz(2:Emm,2:Enm,1:Epmm)+...
    vcoef.viscpp1(:,1:Enmm,1:Epmm).*(vhx(2:Emm,3:En,3:Ep)-vhx(2:Emm,3:En,1:Epmm))+vcoef.viscpm1(:,1:Enmm,1:Epmm).*(vhx(2:Emm,1:Enmm,1:Epmm)-vhx(2:Emm,1:Enmm,3:Ep))...
    +vcoef.viscpp2(:,1:Enmm,1:Epmm).*(vhy(3:Em,2:Enm,3:Ep)-vhy(3:Em,2:Enm,1:Epmm))+vcoef.viscpm2(:,1:Enmm,1:Epmm).*(vhy(1:Emmm,2:Enm,1:Epmm)-vhy(1:Emmm,2:Enm,3:Ep));
    
rz(2:Emm,En,2:Epm)=-vcoef.coefzboundR.*vhz(2:Emm,En,2:Epm)+...
    vcoef.rescoefpp1boundR.*vhz(2:Emm,2,2:Epm)+vcoef.rescoefpm1boundR.*vhz(2:Emm,Enm,2:Epm)+...
    vcoef.rescoefpp2boundR.*vhz(3:Em,En,2:Epm)+vcoef.rescoefpm2boundR.*vhz(1:Emmm,En,2:Epm)+...
    2*vcoef.rescoefpp3boundR.*vhz(2:Emm,En,3:Ep)+2*vcoef.rescoefpm3boundR.*vhz(2:Emm,En,1:Epmm)+...
    vcoef.viscpp1(:,Enm,1:Epmm).*(vhx(2:Emm,2,3:Ep)-vhx(2:Emm,2,1:Epmm))+vcoef.viscpm1(:,Enm,1:Epmm).*(vhx(2:Emm,Enm,1:Epmm)-vhx(2:Emm,Enm,3:Ep))...
    +vcoef.viscpp2(:,Enm,1:Epmm).*(vhy(3:Em,En,3:Ep)-vhy(3:Em,En,1:Epmm))+vcoef.viscpm2(:,Enm,1:Epmm).*(vhy(1:Emmm,En,1:Epmm)-vhy(1:Emmm,En,3:Ep));
    
    
rz(2:Emm,2:Enm,Ep)=-vcoef.coefzboundF.*vhz(2:Emm,2:Enm,Ep)+...
    vcoef.rescoefpp1boundF.*vhz(2:Emm,3:En,Ep)+vcoef.rescoefpm1boundF.*vhz(2:Emm,1:Enmm,Ep)+...
    vcoef.rescoefpp2boundF.*vhz(3:Em,2:Enm,Ep)+vcoef.rescoefpm2boundF.*vhz(1:Emmm,2:Enm,Ep)+...
    2*vcoef.rescoefpm3boundF.*vhz(2:Emm,2:Enm,Epm)+2*vcoef.rescoefpp3boundF.*vhz(2:Emm,2:Enm,2)+...
    vcoef.viscpp1(:,1:Enmm,Epm).*(vhx(2:Emm,3:En,2)-vhx(2:Emm,3:En,Epm))+vcoef.viscpm1(:,1:Enmm,Epm).*(vhx(2:Emm,1:Enmm,Epm)-vhx(2:Emm,1:Enmm,2))...
    +vcoef.viscpp2(:,1:Enmm,Epm).*(vhy(3:Em,2:Enm,2)-vhy(3:Em,2:Enm,Epm))+vcoef.viscpm2(:,1:Enmm,Epm).*(vhy(1:Emmm,2:Enm,Epm)-vhy(1:Emmm,2:Enm,2));

rz(2:Emm,En,Ep)=-vcoef.coefzboundFR.*vhz(2:Emm,En,Ep)+...
    vcoef.rescoefpp1boundFR.*vhz(2:Emm,2,Ep)+vcoef.rescoefpm1boundFR.*vhz(2:Emm,Enm,Ep)+...
    vcoef.rescoefpp2boundFR.*vhz(3:Em,En,Ep)+vcoef.rescoefpm2boundFR.*vhz(1:Emmm,En,Ep)+...
    2*vcoef.rescoefpm3boundFR.*vhz(2:Emm,En,Epm)+2*vcoef.rescoefpp3boundFR.*vhz(2:Emm,En,2)+...
    vcoef.viscpp1(:,Enm,Epm).*(vhx(2:Emm,2,2)-vhx(2:Emm,2,Epm))+vcoef.viscpm1(:,Enm,Epm).*(vhx(2:Emm,Enm,Epm)-vhx(2:Emm,Enm,2))...
    +vcoef.viscpp2(:,Enm,Epm).*(vhy(3:Em,En,2)-vhy(3:Em,En,Epm))+vcoef.viscpm2(:,Enm,Epm).*(vhy(1:Emmm,En,Epm)-vhy(1:Emmm,En,2));

    
rx(:,:,1)=rx(:,:,Ep);
ry(:,:,1)=ry(:,:,Ep);
rz(:,:,1)=rz(:,:,Ep);
rx(:,1,:)=rx(:,En,:);
ry(:,1,:)=ry(:,En,:);
rz(:,1,:)=rz(:,En,:);

rz=-rz;
rx=-rx;
ry=-ry;



end

