function r=residualPRESSUREprod3Dper4(ph,fh,pcoef)
%Computes the residual r=f-Av because Ae=Au-Av=r
[Em,En,Ep]=size(ph);
Emm=Em-1;
Enm=En-1;
Emmm=Em-2;
Enmm=En-2;
Epm=Ep-1;
Epmm=Ep-2;


% Edens=[Edens,Edens(:,2)];
r=zeros(size(ph));
%periodic boundary conditions so the first and last columns of p 
%are equal so we have to concatenate the 2nd column onto the back
%so that we can update the first/last column
% ptemp=[ph,ph(:,2)];


r(2:Emm,2:Enm,2:Epm)=fh(2:Emm,2:Enm,2:Epm)+pcoef.coef(:,1:Enmm,1:Epmm).*ph(2:Emm,2:Enm,2:Epm)-...
    pcoef.rescoefpp1(:,1:Enmm,1:Epmm).*ph(2:Emm,3:En,2:Epm)-pcoef.rescoefpm1(:,1:Enmm,1:Epmm).*ph(2:Emm,1:Enmm,2:Epm)-...
    pcoef.rescoefpp2(:,1:Enmm,1:Epmm).*ph(3:Em,2:Enm,2:Epm)-pcoef.rescoefpm2(:,1:Enmm,1:Epmm).*ph(1:Emmm,2:Enm,2:Epm)-...
    pcoef.rescoefpp3(:,1:Enmm,1:Epmm).*ph(2:Emm,2:Enm,3:Ep)-pcoef.rescoefpm3(:,1:Enmm,1:Epmm).*ph(2:Emm,2:Enm,1:Epmm);

r(2:Emm,2:Enm,Ep)=fh(2:Emm,2:Enm,Ep)+pcoef.coef(:,1:Enmm,Epm).*ph(2:Emm,2:Enm,Ep)-...
    pcoef.rescoefpp1(:,1:Enmm,Epm).*ph(2:Emm,3:En,Ep)-pcoef.rescoefpm1(:,1:Enmm,Epm).*ph(2:Emm,1:Enmm,Ep)-...
    pcoef.rescoefpp2(:,1:Enmm,Epm).*ph(3:Em,2:Enm,Ep)-pcoef.rescoefpm2(:,1:Enmm,Epm).*ph(1:Emmm,2:Enm,Ep)-...
    pcoef.rescoefpp3(:,1:Enmm,Epm).*ph(2:Emm,2:Enm,2)-pcoef.rescoefpm3(:,1:Enmm,Epm).*ph(2:Emm,2:Enm,Epm);
r(2:Emm,2:Enm,1)=r(2:Emm,2:Enm,Ep);  %periodic boundary

r(1,2:Enm,2:Epm)=fh(1,2:Enm,2:Epm)+1/2*(pcoef.coefboundB(1,1:Enmm,1:Epmm).*ph(1,2:Enm,2:Epm)-...
    pcoef.rescoefpp1boundB(1,1:Enmm,1:Epmm).*ph(1,3:En,2:Epm)-pcoef.rescoefpm1boundB(1,1:Enmm,1:Epmm).*ph(1,1:Enmm,2:Epm)-...
    pcoef.rescoefpp2boundB(1,1:Enmm,1:Epmm).*ph(2,2:Enm,2:Epm)-...
    pcoef.rescoefpp3boundB(1,1:Enmm,1:Epmm).*ph(1,2:Enm,3:Ep)-pcoef.rescoefpm3boundB(1,1:Enmm,1:Epmm).*ph(1,2:Enm,1:Epmm));%bottom

r(1,2:Enm,Ep)=fh(1,2:Enm,Ep)+1/2*(pcoef.coefboundB(:,1:Enmm,Epm).*ph(1,2:Enm,Ep)-...
    pcoef.rescoefpp1boundB(:,1:Enmm,Epm).*ph(1,3:En,Ep)-pcoef.rescoefpm1boundB(:,1:Enmm,Epm).*ph(1,1:Enmm,Ep)-...
    pcoef.rescoefpp2boundB(:,1:Enmm,Epm).*ph(2,2:Enm,Ep)-...
    pcoef.rescoefpp3boundB(:,1:Enmm,Epm).*ph(1,2:Enm,2)-pcoef.rescoefpm3boundB(:,1:Enmm,Epm).*ph(1,2:Enm,Epm));%bottom

r(1,En,2:Epm)=fh(1,En,2:Epm)+1/2*(pcoef.coefboundB(:,Enm,1:Epmm).*ph(1,En,2:Epm)-...
    pcoef.rescoefpp1boundB(:,Enm,1:Epmm).*ph(1,2,2:Epm)-pcoef.rescoefpm1boundB(:,Enm,1:Epmm).*ph(1,Enm,2:Epm)-...
    pcoef.rescoefpp2boundB(:,Enm,1:Epmm).*ph(2,En,2:Epm)-...
    pcoef.rescoefpp3boundB(:,Enm,1:Epmm).*ph(1,En,3:Ep)-pcoef.rescoefpm3boundB(:,Enm,1:Epmm).*ph(1,En,1:Epmm));%bottom
    
r(1,En,Ep)=fh(1,En,Ep)+1/2*(pcoef.coefboundB(:,Enm,Epm).*ph(1,En,Ep)-...
    pcoef.rescoefpp1boundB(:,Enm,Epm).*ph(1,2,Ep)-pcoef.rescoefpm1boundB(:,Enm,Epm).*ph(1,Enm,Ep)-...
    pcoef.rescoefpp2boundB(:,Enm,Epm).*ph(2,En,Ep)-...
    pcoef.rescoefpp3boundB(:,Enm,Epm).*ph(1,En,2)-pcoef.rescoefpm3boundB(:,Enm,Epm).*ph(1,En,Epm));%bottom
r(1,En,1)=r(1,En,Ep);
r(1,1,:)=r(1,En,:);
r(1,:,1)=r(1,:,Ep);


r(Em,2:Enm,2:Epm)=fh(Em,2:Enm,2:Epm)+1/2*(pcoef.coefboundT(1,1:Enmm,1:Epmm).*ph(Em,2:Enm,2:Epm)-...
    pcoef.rescoefpp1boundT(1,1:Enmm,1:Epmm).*ph(Em,3:En,2:Epm)-pcoef.rescoefpm1boundT(1,1:Enmm,1:Epmm).*ph(Em,1:Enmm,2:Epm)-...
    pcoef.rescoefpm2boundT(1,1:Enmm,1:Epmm).*ph(Emm,2:Enm,2:Epm)-...
    pcoef.rescoefpp3boundT(1,1:Enmm,1:Epmm).*ph(Em,2:Enm,3:Ep)-pcoef.rescoefpm3boundT(1,1:Enmm,1:Epmm).*ph(Em,2:Enm,1:Epmm));%top

r(Em,2:Enm,Ep)=fh(Em,2:Enm,Ep)+1/2*(pcoef.coefboundT(1,1:Enmm,Epm).*ph(Em,2:Enm,Ep)-...
    pcoef.rescoefpp1boundT(1,1:Enmm,Epm).*ph(Em,3:En,Ep)-pcoef.rescoefpm1boundT(1,1:Enmm,Epm).*ph(Em,1:Enmm,Ep)-...
    pcoef.rescoefpm2boundT(1,1:Enmm,Epm).*ph(Emm,2:Enm,Ep)-...
    pcoef.rescoefpp3boundT(1,1:Enmm,Epm).*ph(Em,2:Enm,2)-pcoef.rescoefpm3boundT(1,1:Enmm,Epm).*ph(Em,2:Enm,Epm));%top

r(Em,En,2:Epm)=fh(Em,En,2:Epm)+1/2*(pcoef.coefboundT(:,Enm,1:Epmm).*ph(Em,En,2:Epm)-...
    pcoef.rescoefpp1boundT(:,Enm,1:Epmm).*ph(Em,2,2:Epm)-pcoef.rescoefpm1boundT(:,Enm,1:Epmm).*ph(Em,Enm,2:Epm)-...
    pcoef.rescoefpm2boundT(:,Enm,1:Epmm).*ph(Emm,En,2:Epm)-...
    pcoef.rescoefpp3boundT(:,Enm,1:Epmm).*ph(Em,En,3:Ep)-pcoef.rescoefpm3boundT(:,Enm,1:Epmm).*ph(Em,En,1:Epmm));%bottom
    
r(Em,En,Ep)=fh(Em,En,Ep)+1/2*(pcoef.coefboundT(:,Enm,Epm).*ph(Em,En,Ep)-...
    pcoef.rescoefpp1boundT(:,Enm,Epm).*ph(Em,2,Ep)-pcoef.rescoefpm1boundT(:,Enm,Epm).*ph(Em,Enm,Ep)-...
    pcoef.rescoefpm2boundT(:,Enm,Epm).*ph(Emm,En,Ep)-...
    pcoef.rescoefpp3boundT(:,Enm,Epm).*ph(Em,En,2)-pcoef.rescoefpm3boundT(:,Enm,Epm).*ph(Em,En,Epm));%bottom
r(Em,En,1)=r(Em,En,Ep);
r(Em,1,:)=r(Em,En,:);
r(Em,:,1)=r(Em,:,Ep);


r(2:Emm,En,2:Epm)=fh(2:Emm,En,2:Epm)+pcoef.coef(:,Enm,1:Epmm).*ph(2:Emm,En,2:Epm)-...
    pcoef.rescoefpp1(:,Enm,1:Epmm).*ph(2:Emm,2,2:Epm)-pcoef.rescoefpm1(:,Enm,1:Epmm).*ph(2:Emm,Enm,2:Epm)-...
    pcoef.rescoefpp2(:,Enm,1:Epmm).*ph(3:Em,En,2:Epm)-pcoef.rescoefpm2(:,Enm,1:Epmm).*ph(1:Emmm,En,2:Epm)-...
    pcoef.rescoefpp3(:,Enm,1:Epmm).*ph(2:Emm,En,3:Ep)-pcoef.rescoefpm3(:,Enm,1:Epmm).*ph(2:Emm,En,1:Epmm);
r(2:Emm,1,2:Epm)=r(2:Emm,En,2:Epm);

r(2:Emm,En,Ep)=fh(2:Emm,En,Ep)+pcoef.coef(:,Enm,Epm).*ph(2:Emm,En,Ep)-...
    pcoef.rescoefpp1(:,Enm,Epm).*ph(2:Emm,2,Ep)-pcoef.rescoefpm1(:,Enm,Epm).*ph(2:Emm,Enm,Ep)-...
    pcoef.rescoefpp2(:,Enm,Epm).*ph(3:Em,En,Ep)-pcoef.rescoefpm2(:,Enm,Epm).*ph(1:Emmm,En,Ep)-...
    pcoef.rescoefpp3(:,Enm,Epm).*ph(2:Emm,En,2)-pcoef.rescoefpm3(:,Enm,Epm).*ph(2:Emm,En,Epm);
r(2:Emm,En,1)=r(2:Emm,En,Ep);
r(2:Emm,1,Ep)=r(2:Emm,En,Ep);
r(2:Emm,1,1)=r(2:Emm,En,Ep);

% r(Em,:,:)=1/2*r(Em,:,:);
% r(1,:,:)=1/2*r(1,:,:);